AWSTemplateFormatVersion: "2010-09-09"
Description: main yml file for s3 bucket deployment
Parameters:
  project:
    Type: String
    Description:  Project Name
    Default: devops-training
  app:
    Type: String
    Description:  Application Name
    Default: app
  env:
    Type: String
    Description:  Environment Name
    Default: dev
  s3ArtifactPath:
    Type: String
    Description: Artifact Bucket Path
    # Default: "https://devops-crosstrack-training.s3.amazonaws.com/code/experienced-resource-training/saad/cfn/services/"
    #Default: "https://devops-crosstrack-training.s3.amazonaws.com/code/saad/cfn/services/"
    Default: "https://static-website-sad.s3.amazonaws.com/code/"

Resources:
  cloudFront:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/cloudfront/cloudfront-app.yml"
      Parameters:
        project: !Ref project
        app: !Ref app
        env: !Ref env
        cfOriginProtocolPolicy: http-only
        s3OriginId: S3 Origin
        s3BucketName: !GetAtt s3Stack.Outputs.s3BucketName
        cfViewerProtocolPolicy: allow-all


Outputs:
  cloudfrontStack:
    Description: cloudfrint stack ID 
    Value: !Ref s3Stack
    Export:
      Name: !Sub "${project}-${app}-${env}-s3StackId-${AWS::Region}"