AWSTemplateFormatVersion: "2010-09-09"
Description: cfn template to deploy s3 bucket

Parameters:
  project:
    Type: String
    Description: Project Name
  env:
    Type: String
    Description: Environment Name
  app:
    Type: String
    Description: App Name

  cfOriginProtocolPolicy:
    Type: String
    Description: Specify protocol that cloudfront will use to connect to origin
    AllowedValues: [http-only, match-viewer, https-only]
  s3OriginId:
    Type: String
    Description: Assign a unique name to the origin
  s3BucketName:
    Type: String
    Description: The S3 bucket name  
  cfViewerProtocolPolicy:
    Type: String
    Description: The protocol that viewers can use to access the origin  
    AllowedValues: [allow-all, https-only, redirect-to-https]

Resources:
  cloudFrontDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:     
        Origins:
          - DomainName: !Sub "${s3BucketName}.s3.${AWS::Region}.amazonaws.com"  
            Id: !Ref s3OriginId
            S3OriginConfig:
              OriginAccessIdentity:
                !Join ['', ['origin-access-identity/cloudfront/', !Ref cloudFrontOriginAccessIdentity]]
            CustomOriginConfig:
              OriginProtocolPolicy: !Ref cfOriginProtocolPolicy
            
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: !Ref s3OriginId
          ViewerProtocolPolicy: !Ref cfViewerProtocolPolicy   
        Enabled: true      
      Tags:
        - Key: name
          Value: !Sub "${project}-${app}-${env}-cloudFrontDistribution"
        - Key: project
          Value: !Ref project
        - Key: app
          Value: !Ref app
        - Key: env
          Value: !Ref env
  cloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: CloudFront Origin AccessIdentity

Outputs:
  cloudFrontDistributionId:
    Value: !Ref cloudFrontDistribution
    Export:
      Name: !Sub "${project}-${app}-${env}-cloudFrontDistributionId-${AWS::Region}"
  # cloudFrontOriginAccessIdentityId: 
  #   Value: !Ref cloudFrontOriginAccessIdentity
  #   Export:
  #     Name: !Sub "${project}-${app}-${env}-cloudFrontOriginAccessIdentityId-${AWS::Region}"


