AWSTemplateFormatVersion: "2010-09-09"
Description: cfn template to deploy s3 bucket

Parameters:
  project:
    Type: String
    Description: Project Name
  env:
    Type: String
    Description: Environment Name
  app:
    Type: String
    Description: App Name
  s3BucketName:
    Type: String
    Description: Bucket Name
  # s3VersioningStatus:
  #   Type: String
  #   Description: Status of Versioning
  #   AllowedValues: [Enabled, Suspended]
  s3IndexDocument:
    Type: String
    Description: The name of the index document for the website
  s3ErrorDocument:
    Type: String
    Description: The name of the error document for the website


Resources:
  s3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub ${project}-${app}-${env}-${s3BucketName}-${AWS::Region}-${AWS::AccountId}
      WebsiteConfiguration:
        IndexDocument: !Ref s3IndexDocument
        ErrorDocument: !Ref s3ErrorDocument
      # VersioningConfiguration:
      #   Status: !Ref s3VersioningStatus
      Tags:
        - Key: name
          Value: !Sub "${project}-${app}-${env}-s3Bucket"
        - Key: project
          Value: !Ref project
        - Key: app
          Value: !Ref app
        - Key: env
          Value: !Ref env

Outputs:
  s3BucketName:
    Description: 
    Value: !Ref s3Bucket
    Export:
      Name: !Sub "${project}-${app}-${env}-s3Bucket-${AWS::Region}"
