AWSTemplateFormatVersion: "2010-09-09"
Description: cfn template to deploy s3 bucket

Parameters:
  project:
    Type: String
    Description: Project Name hehe
  env:
    Type: String
    Description: Environment Name
  app:
    Type: String
    Description: App Name
  s3BucketName:
    Type: String
    Description: Bucket Name
  # s3VersioningStatus:
  #   Type: String
  #   Description: Status of Versioning
  #   AllowedValues: [Enabled, Suspended]
  s3IndexDocument:
    Type: String
    Description: The name of the index document for the website
  s3ErrorDocument:
    Type: String
    Description: The name of the error document for the website
  # cloudFrontOriginAccessIdentity:
  #   Type: String
  #   Description: A cloudfront user associated with s3 origins

Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub ${project}-${app}-${env}-${s3BucketName}-${AWS::Region}-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: !Ref s3IndexDocument
        # ErrorDocument: !Ref s3ErrorDocument
      # VersioningConfiguration:
      #   Status: !Ref s3VersioningStatus
      Tags:
        - Key: name
          Value: !Sub "${project}-${app}-${env}-s3Bucket"
        - Key: project
          Value: !Ref project
        - Key: app
          Value: !Ref app
        - Key: env
          Value: !Ref env

  # SampleBucketPolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Properties:
  #     Bucket: !Ref s3Bucket  #"devops-training-app-dev-static-website-us-east-1-414432075221"
  #     PolicyDocument:
  #       Version: '2012-10-17'
  #       Statement:
  #         - Action:
  #             - '*'
  #           Effect: Allow
  #           Resource:
  #             !Sub arn:aws:s3:::${project}-${app}-${env}-${s3BucketName}-${AWS::Region}-${AWS::AccountId}/*
  #             # - arn:aws:s3:::devops-training-app-dev-static-website-us-east-1-414432075221
  #             # - arn:aws:s3:::devops-training-app-dev-static-website-us-east-1-414432075221/*
  #           Principal: '*'
  
  bucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref s3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Id: ObjectPolicy
        Statement:      
        - Action:
            - s3:GetObject
            - s3:PutObject
          Effect: Allow
          Principal: '*'
            # Service:
            #   - s3.amazonaws.com
          Resource: !Sub arn:aws:s3:::${project}-${app}-${env}-${s3BucketName}-${AWS::Region}-${AWS::AccountId}/*


Outputs:
  s3BucketName:
    Description: s3 bucket name
    Value: !Ref s3Bucket
    Export:
      Name: !Sub "${project}-${app}-${env}-s3Bucket-${AWS::Region}"
