AWSTemplateFormatVersion: "2010-09-09"
Description: main yml file for s3 bucket deployment
Parameters:
  project:
    Type: String
    Description:  Project Name
    Default: devops-training
  app:
    Type: String
    Description:  Application Name
    Default: app
  env:
    Type: String
    Description:  Environment Name
    Default: dev
  s3ArtifactPath:
    Type: String
    Description: Artifact Bucket Path
    # Default: "https://devops-crosstrack-training.s3.amazonaws.com/code/experienced-resource-training/saad/cfn/services/"
    #Default: "https://devops-crosstrack-training.s3.amazonaws.com/code/saad/cfn/services/"
    Default: "https://static-website-sad.s3.amazonaws.com/code/"

Resources:
  s3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}s3/s3-app.yml"
      Parameters:
        project: !Ref project
        app: !Ref app
        env: !Ref env
        s3BucketName: sad-test-static-website
        # s3VersioningStatus: Enabled
        s3IndexDocument: index.html
        s3ErrorDocument: error.html
        # ec2SecurityGroupIds: !ImportValue 
        #   Fn::Sub: "${project}-${app}-${env}-ec2SecurityGroupID-${AWS::Region}"
        # ec2SubnetId: !ImportValue 
        #   Fn::Sub: "${project}-${app}-${env}-publicSubnet01Az01Id-${AWS::Region}"

Outputs:
  s3Stack:
    Description: s3 stack ID 
    Value: !Ref s3Stack
    Export:
      Name: !Sub "${project}-${app}-${env}-s3StackId-${AWS::Region}"
